### ISSUE TITLE
Goroutine Safe

### ISSUE THREAD

**Issue by dubiousdavid** [christopherhesse/rethinkgo#1]
Just wondering why the driver isn't goroutine safe?  Is this a design decision or based on some other best practice or practical limitation.  FYI, I'm new to Go :)

**Comment by christopherhesse** [comment]
Mostly because I haven't had time to work on this since christmas.  It should currently work fine as long as you create a new connection in each goroutine and never use the implicit connection object, meaning

```
query := r.Expr(1, 2, 3).ArrayToStream().Map(r.Row.Mul(2))
// bad
query.Run()
// good
conn.Run(query)
```

**Comment by christopherhesse** [comment]
I implemented some connection pooling and locks, it is not super tested yet, but seems to work well enough.
