### ISSUE TITLE
Fetching all records with exac type returns wrong documents

### ISSUE THREAD

**Issue by robert-zaremba** [christopherhesse/rethinkgo#11]
When fetching all records from table using right map type, the response doesn't contain right records (they all are the same - repetition of the last record).

bug reproduction:

``` go
package main

import (
    r "github.com/christopherhesse/rethinkgo"
    "log"
)

func main() {
    var response r.WriteResponse
    dbs, err := r.Connect("localhost:28015", "test")
    if err != nil {
        log.Fatal("rethink connection error:", err)
    }
    r.TableCreate("test").Run(dbs).Exec()
    r.Table("test").Delete().Run(dbs).Exec()

    var products_in = []map[string]int{
        {"id": 1, "val": 1},
        {"id": 2, "val": 2}}
    err = r.Table("test").Insert(products_in).Run(dbs).One(&response)
    if err != nil {
        log.Fatal("DB insert error:", err)
    }
    log.Println(response)

    var products = new([]map[string]int)
    //var products = new([]interface{})
    err = r.Table("test").Run(dbs).All(products)
    if err != nil {
        log.Fatal("DB insert error:", err)
    }
    log.Println(products)
}
```

Output:

```
&[map[val:2 id:2] map[val:2 id:2]]
```

Expected output:

```
&[map[val:1 id:1] map[val:2 id:2]]
```

If I swap products declaration (lines 26,27) then the response is correct.

**Comment by robert-zaremba** [comment]
When I change the `products` declaration to:

``` go
var products = new([]*map[string]int)
```

Then the issue is more clear. Output:

```
&[0xc2000007f8 0xc2000007f8]
```

**Comment by christopherhesse** [comment]
Thanks for the bug report! I'll check it out later today.  Presumably the problem is in rows.go:

```
    elemValue := reflect.New(sliceValue.Type().Elem())
    for rows.Next() {
        if err := rows.Scan(elemValue.Interface()); err != nil {
            return err
        }
        newSliceValue = reflect.Append(newSliceValue, elemValue.Elem())
    }
```

That elemValue := line should be inside the for rows.Next() loop.  Does that fix your problem?

**Comment by robert-zaremba** [comment]
Yes, it will fix.
But is it possible to optimize it somehow? ie: to left the `elemValue` in its current place and copy it in `newSliceValue = reflect.Append ...`? (I don't know how to copy the value of `elemValue`)

**Comment by robert-zaremba** [comment]
This strange behaviour seams like a bug in Go.

**Comment by christopherhesse** [comment]
Go is a little weird sometimes with some things being reference types, but I suspect that in this case, the only fool-proof way to do this is to declare a new instance each time.

**Comment by robert-zaremba** [comment]
Thanks,
Are you sure, it is not a Go bug?

**Comment by christopherhesse** [comment]
I'm not certain of that, but I think it's very very unlikely.  I could find someway to copy the elemValue, but that would lead to more confusing behavior, like if you have two rows:

```
 {"a": 1}
 {"b": 2}
```

You'd have to zero out elemValue each time, and if elemValue contains pointers, you might have to re-create those.
