### ISSUE TITLE
rethinkdb 1.6

### ISSUE THREAD

**Issue by christopherhesse** [christopherhesse/rethinkgo#12]
Add support for this:

https://groups.google.com/forum/?fromgroups#!topic/rethinkdb-dev/8E1kC02mOlI
http://rethinkdb.com/blog/1.6-release/

Also this might be a good time to remove connection pooling.
Also: clarify use of json module for serializing structs (add to main example program)

**Comment by christopherhesse** [comment]
This will probably not be done until next weekend. 6/22

**Comment by elithrar** [comment]
@christopherhesse Thanks for the heads up Christopher—I'll refrain from upgrading my Rethink install.

**Comment by christopherhesse** [comment]
Should work now, a number of small changes, may require some code updates.
