### ISSUE TITLE
Inconsistent data types when storing  <-> retreating records

### ISSUE THREAD

**Issue by robert-zaremba** [christopherhesse/rethinkgo#15]
When I store a document with an integer field, eg:

```
{"timestamp": 1372809600}
```

stored in DB, then it is right in this form (eg: while quering in http://localhost:8080/#dataexplorer)

But when I want to fetch that data using (because my documents contains more fields of different types):

```
var rows []map[string]interface{}
rdb.Table("quote").Filter(query).Limit(100).Run(dbs).All(&rows);
```

I get:

```
{"timestamp": 1.3728096e+09}
```

they type is: `float64`

Python (which also has rich types for numbers) driver doesn't suffer for this issue.

**Comment by christopherhesse** [comment]
The rethinkdb protocol buffer spec specifically returns a double: https://github.com/christopherhesse/rethinkgo/blob/master/ql2/ql2.proto

```
enum DatumType {
    R_NULL   = 1;
    R_BOOL   = 2;
    R_NUM    = 3; // a double
    R_STR    = 4;
    R_ARRAY  = 5;
    R_OBJECT = 6;
}
```

Is this causing problems for your application?  I'm not sure there's an easy way to fix that.

**Comment by christopherhesse** [comment]
Looks like python loses type information too:

```
type(r.table("test").get(r.table("test").insert({"timestamp": 1372809600.0}).run(conn)["generated_keys"][0]).run(conn)["timestamp"])
```

**Comment by christopherhesse** [comment]
No updates on this, so closing it.

**Comment by pengux** [comment]
One workaround is to convert it to integer by int64(timestamp)

**Comment by robert-zaremba** [comment]
Thanks for inspection.
Sorry for my late response, but I was aok.
In my test Python doesn't loose type information:

```
In [28]: type(r.table("test").get(r.table("test").insert({"timestamp": 1372809600}).run(conn)["generated_keys"][0]).run(conn)["timestamp"])
Out[28]: int

In [29]: type(r.table("test").get(r.table("test").insert({"timestamp": 1372.658}).run(conn)["generated_keys"][0]).run(conn)["timestamp"])
Out[29]: float
```

**Comment by robert-zaremba** [comment]
But it seams (your link about protocol spec) that rethink go internally has only float numbers.

**Comment by christopherhesse** [comment]
Try using 1372.0 in your example.

**Comment by robert-zaremba** [comment]
Right. It is int.

**Comment by christopherhesse** [comment]
So we agree that python is losing type information?

**Comment by robert-zaremba** [comment]
I didn't inspect the sources, but it looks that Python introduce some hacks around numbers. My loose idea is:
- rethinkdb number types are the one from JS. 
  
  ```
  js
  js> 1.0
  1
  ```
- Python tries to to make additional type casting when fetching the data, instead of forcing float type. So in this case Python driver pass the rethinkdb schema.

**Comment by christopherhesse** [comment]
I don't think I'm going to try to guess if a number is an int or not, but you can certainly do that in your code.

**Comment by robert-zaremba** [comment]
I'm fully agree with you!
If the DB supports only one number type then the driver should do the same.
