### ISSUE TITLE
ChangeAt(index, json) uses int type for index, should it use Expr?

### ISSUE THREAD

**Issue by nimajalali** [christopherhesse/rethinkgo#18]
I'm trying to change an object within an array. Problem is I don't know the index of the object ahead of time.

To get the index I use indexesOf with a function that looks for the specific object. IndexesOf pulls an array of indexes that match but I just need the first index so I use nth(0) to grab the first index in the array.

ReQL command

```
r.db('test').table('users').get("e744a17f-5da9-4394-af22-3d3eda1ff08c").update(
     { "someArray": r.row('someArray').changeAt(r.row('someArray').indexesOf( 
          function(item) { 
              return item('name').eq('TEST');
          }).nth(0), {"name":"TEST2"})
     }
)
```

I'm attempting to convert this from the JS syntax to rethinkgo. Here is my attempt

```
// The function used to find the drop
query := func(row r.Exp) r.Exp { return row.Attr("name").Eq("test123") }

err = r.Table("users").Get("e744a17f-5da9-4394-af22-3d3eda1ff08c").Update( r.Map{"someArray": r.Row.Attr("someArray").ChangeAt( r.Row.Attr("someArray").IndexesOf(query).Nth(0), r.Map{"name":"TEST2"}) 
}).Run(session).One(&response)
```

The implementation of IndexesOf requires an int to be passed in for the index. However the Nth function returns an Expr. Any reason IndexsOf can't accept an Expr for the index?

I could easily break this up into two queries but I'd rather keep it in one. 

I could also add another function that does everything IndexesOf does and change index to have the type r.Expr. But I wanted to see if I'm on the right track, any recommendations would be greatly appreciated.

**Comment by christopherhesse** [comment]
I'm guessing that all functions that take an int instead of an expr are wrong then.  I'll give it a shot, should be straightforward.

**Comment by christopherhesse** [comment]
Should be fixed in 

https://github.com/christopherhesse/rethinkgo/commit/3dee2916f355afde0deddb3e076fdcfe53e41385

Let me know if this doesn't work for you.

**Comment by christopherhesse** [comment]
Oh yeah, thanks for the well written bug report!

**Comment by nimajalali** [comment]
Works Great!

I also found that using r.Js() with the query object I had below, caused rethink to be unable to prove the function deterministic.

```
query := fmt.Sprintf(`function (item) { return item('name').eq('%v');}`, name)
```

I replaced it with the following and it works great. (Also edited in original issue)

```
query := func(row r.Exp) r.Exp { return row.Attr("name").Eq("test123") }
```

Thanks for the help!
