### ISSUE TITLE
Needs update to new protocol

### ISSUE THREAD

**Issue by hugo** [christopherhesse/rethinkgo#2]
RethinkDB 1.4 introduced a new wire protocol. As such, trying to use rethinkgo with the latest version returns the error `read tcp 127.0.0.1:28015: connection reset by peer`

**Comment by christopherhesse** [comment]
Thanks for filing the issue, I am aware and will hopefully get to fix it later this week/weekend.  Workaround for now is of course to use the older version ;)

**Comment by christopherhesse** [comment]
Beta version of new protocol compatibility at https://github.com/christopherhesse/rethinkgo/tree/query-language-2

I'll finish it up next weekend.

**Comment by hugo** [comment]
Fantastic; I'll give it a go tonight and report any issues.

**Comment by ConceitedCode** [comment]
Just ran the tests and tried it with my project and haven't found any problems yet. Is there anything I should watch out for or any known issues with that branch or is it pretty much ready to be used?

**Comment by hugo** [comment]
I've been using it for the last week or so; haven't encountered any problems, but I'm not doing anything all that complex.

**Comment by christopherhesse** [comment]
Thanks for the help guys, I wasn't able to finish it up last weekend, but hopefully will have time to clean up this branch and merge it to master soon.

**Comment by christopherhesse** [comment]
I did the remainder of the cleanup, should be good to go.
