### ISSUE TITLE
Update the driver to Rethinkdb 1.9

### ISSUE THREAD

**Issue by ekanna** [christopherhesse/rethinkgo#26]
Hi,

Please update this to rethinkdb 1.9
Is there any idea to convert this as a official golang driver for rethinkdb?

**Comment by dancannon** [comment]
I don't believe there were any changes to ReQL in 1.9 so there shouldn't need to be any changes to the driver.

**Comment by ekanna** [comment]
@dancannon If that is the case, it will be nice if Readme page is updated accordingly. Right now, the impression is it supports only 1.7 and not even 1.8

**Comment by dancannon** [comment]
Right now my 1.8 PR is mostly functional and should be fine for use however it has not been fully tested and as such has not been merged

**Comment by ekanna** [comment]
Please update this!

**Comment by ekanna** [comment]
@christopherhesse Please update this! I am working on a new golang project. I have chosen rethinkdb! But lack of up to date  driver for golang making me rethink on rethinkdb!

**Comment by nimajalali** [comment]
@ekanna The driver supports all ReQL commands up to RethinkDB 1.7 but will work just fine with RethinkDB 1.9

1.8 introduced a few additions to ReQL and as such @dancannon has create an updated driver, see #24 

1.9 did not have any ReQL updates.

There were no breaking changes made in the 1.8 or 1.9 release. Just a few additions in 1.8. So the driver still works. I'm currently using the master branch against RethinkDB 1.9 in production.

**Comment by dancannon** [comment]
I have also started a new driver which is based on this one but is better setup to deal with the new Pseudo-Types. There are still a couple of things left to sort out (Connection pools for one thing) but the rest of the driver should work fine.

https://github.com/dancannon/gorethink

**Comment by christopherhesse** [comment]
@ekanna I am afraid that I don't currently have the time to update this driver.  Anyone is welcome to update it, or you could talk to the rethinkdb guys and tell them you're interested in an official go driver.  dancannon's driver is also an option.

**Comment by ekanna** [comment]
Thank you all for updating the status.
