### ISSUE TITLE
Is there another dependency I need to be aware of?

### ISSUE THREAD

**Issue by Altonymous** [christopherhesse/rethinkgo#5]
I used brew install rethinkdb.
I used brew install mercurial .

I pulled the sample code from your README.

$ go build rethinkdb.go
# command-line-arguments
./rethinkdb.go:10: too many arguments in call to rethinkgo.Expr
./rethinkdb.go:10: rethinkgo.Expr(1, 2, 3).ArrayToStream undefined (type rethinkgo.Exp has no field or method ArrayToStream)

**Comment by christopherhesse** [comment]
I probably did not update the code sample in the readme for the new version of rethinkdb, I'll look at this tonight.

**Comment by christopherhesse** [comment]
I updated the README.  Thanks for the bug report!
