### ISSUE TITLE
Able to create a table but not drop it?

### ISSUE THREAD

**Issue by Altonymous** [christopherhesse/rethinkgo#6]
With the below code I am able to create a table in the test database.  However, it doesn't drop.  I get no errors, it just seems to think it worked.  But checking the Admin UI shows the table still exists.

  session, _ := r.Connect("localhost:28015", "test")
  r.TableCreate("tv_shows").Run(session)
  r.TableDrop("tv_shows").Run(session)

I should also note that I am able to drop the table from the DataExplorer UI without issue.

**Comment by Altonymous** [comment]
I take that back.. there is an error...

error: rethinkdb: Server could not make sense of our query: [type:R_STR r_str:"Expected 2 argument(s) but found 1." ] []

So then I checked the source code and found that for some reason it doesn't use the Db defined in the session created like TableCreate does...

So I used this instead and it works.

  rows = r.Db("test").TableDrop("tv_shows").Run(session)

Is that an oversight?

**Comment by christopherhesse** [comment]
Almost for sure, I refactored that code with the new release of rethinkdb and it looks like I missed a couple of use cases.  I'll look at it tonight.

**Comment by christopherhesse** [comment]
Thanks for the bug report! This should be fixed in master.

I'm inclined to remove the database name from the session entirely, but then maybe you'd need to pass the database and session around separately.

Hopefully this is the only remaining call that uses an implicit database, besides the normal query stuff.
